# Generated by Django 4.0.1 on 2022-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0002_employee_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='field',
            field=models.ImageField(upload_to=''),
        ),
    ]
