# Generated by Django 4.0.1 on 2022-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0003_alter_employee_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='field',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
